#!/bin/bash
# https://wiki.archlinux.org/title/Dwm#Restart_dwm

# Autostart Items
picom -b # Compositor

csum=""
new_csum=$(sha1sum $(which dwm))
while true
do
    if [ "$csum" != "$new_csum" ]
    then
        csum=$new_csum
	pasystray &
	nitrogen --restore
	nm-applet --indicator &
	xfce4-power-manager &
	copyq --start-server
        dwm
    else
        exit 0
    fi
    new_csum=$(sha1sum $(which dwm))
    sleep 0.5
done
